Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print('  Z:',hnuc.Z)
print('  A:',hnuc.A)
print(' ch:',hnuc.ch)
print('lre:',hnuc.lre)
print('lre_err:',hnuc.lre_err)
------------------

----- stdout -----
  Z: [ 1  1  2  2  2  2  2  3  3  3  4  4  4  4  4  5  5  5  5  5  5  5  6  6
  6  6  6  6  6  6  6  6  7  7  8  8 14 14 14 16 16 16 20 20 23 23 23 23
 39 39 39 39 39 57 57 57 57 57 82 82 82 82 82]
  A: [  3   4   4   5   6   7   8   7   8   9   7   8   9  10  10   9  10  10
  11  12  12  12  12  12  12  12  13  13  13  13  13  14  16  16  16  16
  28  28  28  32  32  32  40  40  51  51  51  52  89  89  89  89  89 139
 139 139 139 139 208 208 208 208 208]
------------------

[31m---------------------------------------------------------------------------[39m
[31mAttributeError[39m                            Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[6][39m[32m, line 3[39m
[32m      1[39m [38;5;28mprint[39m([33m'[39m[33m  Z:[39m[33m'[39m,hnuc.Z)
[32m      2[39m [38;5;28mprint[39m([33m'[39m[33m  A:[39m[33m'[39m,hnuc.A)
[32m----> [39m[32m3[39m [38;5;28mprint[39m([33m'[39m[33m ch:[39m[33m'[39m,[43mhnuc[49m[43m.[49m[43mch[49m)
[32m      4[39m [38;5;28mprint[39m([33m'[39m[33mlre:[39m[33m'[39m,hnuc.lre)
[32m      5[39m [38;5;28mprint[39m([33m'[39m[33mlre_err:[39m[33m'[39m,hnuc.lre_err)

[31mAttributeError[39m: 'setupRE1LExp' object has no attribute 'ch'

